apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # echo -n 'your-password' | base64
  password: cGFzc3dvcmQ=  # base64 encoded 'password'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # Replace with your RDS endpoint
  host: "your-rds-endpoint.amazonaws.com"
  port: "5432"
  database: "notes_app"
  username: "postgres"