- name: Setup Docker and Kubernetes on EC2 instance
  hosts: servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Add 'ubuntu' user to the 'docker' group
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Install kubectl
      snap:
        name: kubectl
        classic: yes